services:
  app:
    image: ghcr.io/artroxgabriel/local-meeting-pipeline:cpu
    build:
      context: .
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    volumes:
      - .:/workspace
      - huggingface-cache:/root/.cache/huggingface
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - ENABLE_GPU=false
    depends_on:
      ollama-pull-model:
        condition: service_completed_successfully

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

  ollama-pull-model:
    image: ollama/ollama:latest
    environment:
      - OLLAMA_HOST=ollama:11434
    command: ["pull", "LiquidAI/lfm2.5-1.2b-instruct"]
    depends_on:
      - ollama

volumes:
  ollama-data:
  huggingface-cache:
